[package]
name = "galaxy"
version = "0.1.0"
authors = ["Akash <amelachuri@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_fly_camera = "0.7"
rand = "0.7.3"
